# Run Biome on staged files that have the following extensions: js, ts, jsx, tsx, json and jsonc
#"*.{js,ts,cjs,mjs,d.cts,d.mts,jsx,tsx,json,jsonc}":
#  # Check formatting and lint
#  - "biome check --files-ignore-unknown=true"
#  # Format, sort imports, lint, and apply safe fixes
#  - "biome check --write --no-errors-on-unmatched"
#  # format and apply safe fixes
#  - "biome check --write --organize-imports-enabled=false --no-errors-on-unmatched"
#  # Format, sort imports, lints, apply safe/unsafe fixes
#  - "biome check --write --unsafe --no-errors-on-unmatched"
#  # Format
#  - "biome format --write --no-errors-on-unmatched"
#  # Lint and apply safe fixes
#  - "biome lint --write --no-errors-on-unmatched"
# Alternatively you can pass every files and ignore unknown extensions
"*": "biome check --write --no-errors-on-unmatched --files-ignore-unknown=true"
