import type { NewMedicationCatalog } from "../schema";

export const commonVeterinaryMedications: Omit<
  NewMedicationCatalog,
  "id" | "createdAt" | "updatedAt"
>[] = [
  // Antibiotics
  {
    brandName: "Amoxi-Tabs",
    commonDosing: "10-20mg/kg BID",
    controlledSubstance: false,
    form: "TABLET",
    genericName: "Amoxicillin",
    route: "ORAL",
    strength: "50mg",
    warnings: "Complete full course even if symptoms improve",
  },
  {
    brandName: "Amoxi-Tabs",
    commonDosing: "10-20mg/kg BID",
    controlledSubstance: false,
    form: "TABLET",
    genericName: "Amoxicillin",
    route: "ORAL",
    strength: "100mg",
    warnings: "Complete full course even if symptoms improve",
  },
  {
    brandName: "Amoxi-Tabs",
    commonDosing: "10-20mg/kg BID",
    controlledSubstance: false,
    form: "TABLET",
    genericName: "Amoxicillin",
    route: "ORAL",
    strength: "200mg",
    warnings: "Complete full course even if symptoms improve",
  },
  {
    brandName: "Rilexine",
    commonDosing: "15-25mg/kg BID",
    controlledSubstance: false,
    form: "TABLET",
    genericName: "Cephalexin",
    route: "ORAL",
    strength: "75mg",
    warnings: "Give with food to reduce stomach upset",
  },
  {
    brandName: "Rilexine",
    commonDosing: "15-25mg/kg BID",
    controlledSubstance: false,
    form: "TABLET",
    genericName: "Cephalexin",
    route: "ORAL",
    strength: "300mg",
    warnings: "Give with food to reduce stomach upset",
  },
  {
    brandName: "Baytril",
    commonDosing: "5mg/kg SID",
    controlledSubstance: false,
    form: "TABLET",
    genericName: "Enrofloxacin",
    route: "ORAL",
    strength: "22.7mg",
    warnings: "Avoid dairy products, monitor for joint issues in young animals",
  },
  {
    brandName: "Baytril",
    commonDosing: "5mg/kg SID",
    controlledSubstance: false,
    form: "TABLET",
    genericName: "Enrofloxacin",
    route: "ORAL",
    strength: "68mg",
    warnings: "Avoid dairy products, monitor for joint issues in young animals",
  },
  {
    brandName: "Antirobe",
    commonDosing: "5-10mg/kg BID",
    controlledSubstance: false,
    form: "CAPSULE",
    genericName: "Clindamycin",
    route: "ORAL",
    strength: "25mg",
    warnings: "Give with food, watch for diarrhea",
  },
  {
    brandName: "Antirobe",
    commonDosing: "5-10mg/kg BID",
    controlledSubstance: false,
    form: "CAPSULE",
    genericName: "Clindamycin",
    route: "ORAL",
    strength: "75mg",
    warnings: "Give with food, watch for diarrhea",
  },
  {
    brandName: "Flagyl",
    commonDosing: "7.5mg/kg BID",
    controlledSubstance: false,
    form: "TABLET",
    genericName: "Metronidazole",
    route: "ORAL",
    strength: "250mg",
    warnings: "Neurological side effects possible at high doses",
  },

  // Diabetes & Endocrine
  {
    brandName: "Lantus",
    commonDosing: "Cats: 0.25-0.5 U/kg SC BID. Dogs: 0.25-0.5 U/kg SC BID",
    controlledSubstance: false,
    form: "INJECTION",
    genericName: "Insulin glargine",
    route: "SC",
    strength: "100 units/mL",
    warnings: "Refrigerate. Monitor blood glucose. Never shake vial.",
  },
  {
    brandName: "Humulin N",
    commonDosing: "Dogs: 0.5 U/kg SC BID. Cats: 1-3 U per cat BID",
    controlledSubstance: false,
    form: "INJECTION",
    genericName: "Insulin NPH",
    route: "SC",
    strength: "100 units/mL",
    warnings: "Refrigerate. Roll gently to mix. Monitor blood glucose.",
  },
  {
    brandName: "Levemir",
    commonDosing: "Cats: 0.5-1 U/kg SC BID",
    controlledSubstance: false,
    form: "INJECTION",
    genericName: "Insulin detemir",
    route: "SC",
    strength: "100 units/mL",
    warnings: "Refrigerate. Do not mix with other insulins.",
  },
  {
    brandName: "Lantus SoloStar",
    commonDosing: "Cats: 0.25-0.5 U/kg SC BID",
    controlledSubstance: false,
    form: "INJECTION",
    genericName: "Insulin glargine",
    route: "SC",
    strength: "40 units",
    warnings:
      "Pre-filled pen. Refrigerate. Do not shake. Prime before first use.",
  },

  // Pain Management & NSAID's
  {
    brandName: "Rimadyl",
    commonDosing: "2mg/kg BID or 4mg/kg SID",
    controlledSubstance: false,
    form: "TABLET",
    genericName: "Carprofen",
    route: "ORAL",
    strength: "25mg",
    warnings: "Monitor liver and kidney function, give with food",
  },
  {
    brandName: "Rimadyl",
    commonDosing: "2mg/kg BID or 4mg/kg SID",
    controlledSubstance: false,
    form: "TABLET",
    genericName: "Carprofen",
    route: "ORAL",
    strength: "75mg",
    warnings: "Monitor liver and kidney function, give with food",
  },
  {
    brandName: "Rimadyl",
    commonDosing: "2mg/kg BID or 4mg/kg SID",
    controlledSubstance: false,
    form: "TABLET",
    genericName: "Carprofen",
    route: "ORAL",
    strength: "100mg",
    warnings: "Monitor liver and kidney function, give with food",
  },
  {
    brandName: "Metacam",
    commonDosing: "0.1mg/kg SID",
    controlledSubstance: false,
    form: "LIQUID",
    genericName: "Meloxicam",
    route: "ORAL",
    strength: "0.5mg/ml",
    warnings: "Administer precise dose, monitor for GI upset",
  },
  {
    brandName: "Metacam",
    commonDosing: "0.1mg/kg SID",
    controlledSubstance: false,
    form: "LIQUID",
    genericName: "Meloxicam",
    route: "ORAL",
    strength: "1.5mg/ml",
    warnings: "Administer precise dose, monitor for GI upset",
  },
  {
    brandName: null,
    commonDosing: "5-10mg/kg BID-TID",
    controlledSubstance: false,
    form: "CAPSULE",
    genericName: "Gabapentin",
    route: "ORAL",
    strength: "100mg",
    warnings: "Start with low dose and titrate up, causes sedation initially",
  },
  {
    brandName: null,
    commonDosing: "5-10mg/kg BID-TID",
    controlledSubstance: false,
    form: "CAPSULE",
    genericName: "Gabapentin",
    route: "ORAL",
    strength: "300mg",
    warnings: "Start with low dose and titrate up, causes sedation initially",
  },
  {
    brandName: null,
    commonDosing: "2-5mg/kg BID-TID",
    controlledSubstance: true,
    form: "TABLET",
    genericName: "Tramadol",
    route: "ORAL",
    strength: "50mg",
    warnings: "Controlled substance, may cause sedation or excitement",
  },

  // Controlled Substances / Opioids
  {
    brandName: "Buprenex",
    commonDosing: "0.01-0.03mg/kg q6-12h",
    controlledSubstance: true,
    form: "INJECTION",
    genericName: "Buprenorphine",
    route: "SC",
    strength: "0.3mg/ml",
    warnings: "Controlled substance, respiratory depression possible",
  },
  {
    brandName: null,
    commonDosing: "0.1-1mg/kg q4-6h",
    controlledSubstance: true,
    form: "INJECTION",
    genericName: "Morphine",
    route: "IM",
    strength: "10mg/ml",
    warnings: "Controlled substance, monitor respiratory function",
  },

  // Sedatives/Anxiolytics
  {
    brandName: "PromAce",
    commonDosing: "0.25-1mg/kg PRN",
    controlledSubstance: false,
    form: "TABLET",
    genericName: "Acepromazine",
    route: "ORAL",
    strength: "10mg",
    warnings: "Do not use in seizure-prone animals, causes hypotension",
  },
  {
    brandName: "PromAce",
    commonDosing: "0.01-0.05mg/kg PRN",
    controlledSubstance: false,
    form: "INJECTION",
    genericName: "Acepromazine",
    route: "IM",
    strength: "10mg/ml",
    warnings: "Do not use in seizure-prone animals, causes hypotension",
  },
  {
    brandName: null,
    commonDosing: "2-5mg/kg BID PRN",
    controlledSubstance: false,
    form: "TABLET",
    genericName: "Trazodone",
    route: "ORAL",
    strength: "50mg",
    warnings: "May cause sedation, monitor for serotonin syndrome",
  },
  {
    brandName: "Xanax",
    commonDosing: "0.01-0.05mg/kg PRN",
    controlledSubstance: true,
    form: "TABLET",
    genericName: "Alprazolam",
    route: "ORAL",
    strength: "0.25mg",
    warnings: "Controlled substance, may cause paradoxical excitement",
  },

  // Cardiac Medications
  {
    brandName: "Enacard",
    commonDosing: "0.25-0.5mg/kg BID",
    controlledSubstance: false,
    form: "TABLET",
    genericName: "Enalapril",
    route: "ORAL",
    strength: "2.5mg",
    warnings: "Monitor kidney function and blood pressure",
  },
  {
    brandName: "Enacard",
    commonDosing: "0.25-0.5mg/kg BID",
    controlledSubstance: false,
    form: "TABLET",
    genericName: "Enalapril",
    route: "ORAL",
    strength: "5mg",
    warnings: "Monitor kidney function and blood pressure",
  },
  {
    brandName: "Lasix",
    commonDosing: "1-2mg/kg BID-TID",
    controlledSubstance: false,
    form: "TABLET",
    genericName: "Furosemide",
    route: "ORAL",
    strength: "12.5mg",
    warnings: "Monitor electrolytes and kidney function",
  },
  {
    brandName: "Lasix",
    commonDosing: "1-2mg/kg BID-TID",
    controlledSubstance: false,
    form: "TABLET",
    genericName: "Furosemide",
    route: "ORAL",
    strength: "50mg",
    warnings: "Monitor electrolytes and kidney function",
  },
  {
    brandName: "Vetmedin",
    commonDosing: "0.25mg/kg BID",
    controlledSubstance: false,
    form: "CAPSULE",
    genericName: "Pimobendan",
    route: "ORAL",
    strength: "1.25mg",
    warnings: "Give on empty stomach, monitor for arrhythmias",
  },
  {
    brandName: "Vetmedin",
    commonDosing: "0.25mg/kg BID",
    controlledSubstance: false,
    form: "CAPSULE",
    genericName: "Pimobendan",
    route: "ORAL",
    strength: "2.5mg",
    warnings: "Give on empty stomach, monitor for arrhythmias",
  },

  // Gastrointestinal
  {
    brandName: "Prilosec",
    commonDosing: "0.5-1mg/kg SID",
    controlledSubstance: false,
    form: "CAPSULE",
    genericName: "Omeprazole",
    route: "ORAL",
    strength: "20mg",
    warnings: "Give on empty stomach, long-term use may affect B12 absorption",
  },
  {
    brandName: "Pepcid",
    commonDosing: "0.25-0.5mg/kg BID",
    controlledSubstance: false,
    form: "TABLET",
    genericName: "Famotidine",
    route: "ORAL",
    strength: "10mg",
    warnings: "Safe for most animals, may interfere with some medications",
  },
  {
    brandName: "Cerenia",
    commonDosing: "2mg/kg SID",
    controlledSubstance: false,
    form: "TABLET",
    genericName: "Maropitant",
    route: "ORAL",
    strength: "16mg",
    warnings: "For prevention of motion sickness and vomiting",
  },
  {
    brandName: "Cerenia",
    commonDosing: "2mg/kg SID",
    controlledSubstance: false,
    form: "TABLET",
    genericName: "Maropitant",
    route: "ORAL",
    strength: "24mg",
    warnings: "For prevention of motion sickness and vomiting",
  },
  {
    brandName: "Carafate",
    commonDosing: "0.5-1g TID",
    controlledSubstance: false,
    form: "TABLET",
    genericName: "Sucralfate",
    route: "ORAL",
    strength: "1g",
    warnings: "Give on empty stomach, may bind other medications",
  },

  // Antihistamines/Allergy
  {
    brandName: "Benadryl",
    commonDosing: "1mg/kg BID-TID",
    controlledSubstance: false,
    form: "TABLET",
    genericName: "Diphenhydramine",
    route: "ORAL",
    strength: "25mg",
    warnings:
      "Causes drowsiness, avoid preparations with other active ingredients",
  },
  {
    brandName: "Claritin",
    commonDosing: "0.25mg/kg SID",
    controlledSubstance: false,
    form: "TABLET",
    genericName: "Loratadine",
    route: "ORAL",
    strength: "10mg",
    warnings: "Non-sedating antihistamine",
  },
  {
    brandName: "Zyrtec",
    commonDosing: "0.25-0.5mg/kg SID",
    controlledSubstance: false,
    form: "TABLET",
    genericName: "Cetirizine",
    route: "ORAL",
    strength: "10mg",
    warnings: "May cause mild sedation",
  },
  {
    brandName: "Atarax",
    commonDosing: "1-2mg/kg BID-TID",
    controlledSubstance: false,
    form: "TABLET",
    genericName: "Hydroxyzine",
    route: "ORAL",
    strength: "10mg",
    warnings: "Sedating antihistamine, useful for anxiety",
  },

  // Seizure Medications
  {
    brandName: null,
    commonDosing: "1-3mg/kg BID",
    controlledSubstance: true,
    form: "TABLET",
    genericName: "Phenobarbital",
    route: "ORAL",
    strength: "15mg",
    warnings: "Controlled substance, monitor liver function and drug levels",
  },
  {
    brandName: null,
    commonDosing: "1-3mg/kg BID",
    controlledSubstance: true,
    form: "TABLET",
    genericName: "Phenobarbital",
    route: "ORAL",
    strength: "30mg",
    warnings: "Controlled substance, monitor liver function and drug levels",
  },
  {
    brandName: "K-BroVet",
    commonDosing: "15-30mg/kg SID",
    controlledSubstance: false,
    form: "LIQUID",
    genericName: "Potassium Bromide",
    route: "ORAL",
    strength: "250mg/ml",
    warnings: "Give with food, long loading period required",
  },
  {
    brandName: "Keppra",
    commonDosing: "10-20mg/kg TID",
    controlledSubstance: false,
    form: "TABLET",
    genericName: "Levetiracetam",
    route: "ORAL",
    strength: "250mg",
    warnings: "Relatively safe, may cause sedation initially",
  },

  // Thyroid Medications
  {
    brandName: "Soloxine",
    commonDosing: "10-20mcg/kg BID",
    controlledSubstance: false,
    form: "TABLET",
    genericName: "Levothyroxine",
    route: "ORAL",
    strength: "0.1mg",
    warnings: "Give on empty stomach, monitor T4 levels",
  },
  {
    brandName: "Soloxine",
    commonDosing: "10-20mcg/kg BID",
    controlledSubstance: false,
    form: "TABLET",
    genericName: "Levothyroxine",
    route: "ORAL",
    strength: "0.2mg",
    warnings: "Give on empty stomach, monitor T4 levels",
  },
  {
    brandName: "Soloxine",
    commonDosing: "10-20mcg/kg BID",
    controlledSubstance: false,
    form: "TABLET",
    genericName: "Levothyroxine",
    route: "ORAL",
    strength: "0.5mg",
    warnings: "Give on empty stomach, monitor T4 levels",
  },
  {
    brandName: "Tapazole",
    commonDosing: "2.5-5mg BID",
    controlledSubstance: false,
    form: "TABLET",
    genericName: "Methimazole",
    route: "ORAL",
    strength: "2.5mg",
    warnings: "Monitor CBC and liver function, for hyperthyroidism",
  },

  // Topical/Ophthalmic/Otic
  {
    brandName: "Gentocin Otic",
    commonDosing: "2-4 drops BID",
    controlledSubstance: false,
    form: "DROPS",
    genericName: "Gentamicin/Betamethasone",
    route: "OTIC",
    strength: "3mg/ml + 1mg/ml",
    warnings: "For ear infections, do not use if eardrum is ruptured",
  },
  {
    brandName: "Tobradex",
    commonDosing: "1-2 drops TID-QID",
    controlledSubstance: false,
    form: "DROPS",
    genericName: "Tobramycin/Dexamethasone",
    route: "OPHTHALMIC",
    strength: "3mg/ml + 1mg/ml",
    warnings: "For eye infections, avoid with viral conditions",
  },
  {
    brandName: "OptixCare",
    commonDosing: "1-2 drops PRN",
    controlledSubstance: false,
    form: "DROPS",
    genericName: "Artificial Tears",
    route: "OPHTHALMIC",
    strength: null,
    warnings: "Safe for frequent use",
  },
  {
    brandName: "Muricin",
    commonDosing: "Apply TID",
    controlledSubstance: false,
    form: "OINTMENT",
    genericName: "Mupirocin",
    route: "TOPICAL",
    strength: "2%",
    warnings: "For skin infections, avoid contact with eyes",
  },
  {
    brandName: "Silvadene",
    commonDosing: "Apply BID",
    controlledSubstance: false,
    form: "CREAM",
    genericName: "Silver Sulfadiazine",
    route: "TOPICAL",
    strength: "1%",
    warnings: "For burn treatment, may cause temporary skin discoloration",
  },

  // Supplements/Vitamins
  {
    brandName: "Welactin",
    commonDosing: "1 capsule per 30lbs daily",
    controlledSubstance: false,
    form: "CAPSULE",
    genericName: "Omega-3 Fatty Acids",
    route: "ORAL",
    strength: "1000mg",
    warnings: "Support for skin, coat, and joint health",
  },
  {
    brandName: "Cosequin",
    commonDosing: "1 tablet per 25lbs daily",
    controlledSubstance: false,
    form: "TABLET",
    genericName: "Glucosamine/Chondroitin",
    route: "ORAL",
    strength: "500mg/400mg",
    warnings: "Joint support supplement, may take 4-6 weeks to see effects",
  },
  {
    brandName: "FortiFlora",
    commonDosing: "1 packet daily",
    controlledSubstance: false,
    form: "POWDER",
    genericName: "Probiotics",
    route: "ORAL",
    strength: "1g",
    warnings: "Digestive support, store in cool dry place",
  },

  // Parasiticides
  {
    brandName: "Heartgard",
    commonDosing: "6mcg/kg monthly",
    controlledSubstance: false,
    form: "TABLET",
    genericName: "Ivermectin",
    route: "ORAL",
    strength: "68mcg",
    warnings: "Contraindicated in MDR1 mutation breeds, heartworm prevention",
  },
  {
    brandName: "Frontline",
    commonDosing: "Apply monthly",
    controlledSubstance: false,
    form: "SPRAY",
    genericName: "Fipronil",
    route: "TOPICAL",
    strength: "9.8%",
    warnings: "Flea and tick prevention, avoid contact with treated areas",
  },
  {
    brandName: "Advantage Multi",
    commonDosing: "Apply monthly",
    controlledSubstance: false,
    form: "DROPS",
    genericName: "Imidacloprid/Moxidectin",
    route: "TOPICAL",
    strength: "10%/2.5%",
    warnings: "Broad spectrum parasite prevention",
  },
  {
    brandName: "Nemex",
    commonDosing: "5mg/kg, repeat in 2 weeks",
    controlledSubstance: false,
    form: "LIQUID",
    genericName: "Pyrantel Pamoate",
    route: "ORAL",
    strength: "50mg/ml",
    warnings: "Deworming medication, safe for puppies and kittens",
  },

  // Emergency/Injectable
  {
    brandName: "EpiPen",
    commonDosing: "0.01mg/kg IM",
    controlledSubstance: false,
    form: "INJECTION",
    genericName: "Epinephrine",
    route: "IM",
    strength: "1mg/ml",
    warnings: "Emergency use only for anaphylaxis",
  },
  {
    brandName: "Azium",
    commonDosing: "0.1-2mg/kg",
    controlledSubstance: false,
    form: "INJECTION",
    genericName: "Dexamethasone",
    route: "IV",
    strength: "2mg/ml",
    warnings: "Potent anti-inflammatory, multiple drug interactions",
  },
  {
    brandName: null,
    commonDosing: "0.02-0.04mg/kg",
    controlledSubstance: false,
    form: "INJECTION",
    genericName: "Atropine",
    route: "IM",
    strength: "0.5mg/ml",
    warnings: "For organophosphate poisoning and bradycardia",
  },

  // Additional Common Medications
  {
    brandName: null,
    commonDosing: "0.5-2mg/kg SID-BID",
    controlledSubstance: false,
    form: "TABLET",
    genericName: "Prednisone",
    route: "ORAL",
    strength: "5mg",
    warnings:
      "Taper dose gradually, monitor for side effects with long-term use",
  },
  {
    brandName: null,
    commonDosing: "0.5-2mg/kg SID-BID",
    controlledSubstance: false,
    form: "TABLET",
    genericName: "Prednisone",
    route: "ORAL",
    strength: "10mg",
    warnings:
      "Taper dose gradually, monitor for side effects with long-term use",
  },
  {
    brandName: null,
    commonDosing: "0.5-2mg/kg SID-BID",
    controlledSubstance: false,
    form: "TABLET",
    genericName: "Prednisolone",
    route: "ORAL",
    strength: "5mg",
    warnings: "Preferred over prednisone in cats, taper dose gradually",
  },
  {
    brandName: "Atopica",
    commonDosing: "5mg/kg SID",
    controlledSubstance: false,
    form: "CAPSULE",
    genericName: "Cyclosporine",
    route: "ORAL",
    strength: "25mg",
    warnings: "For atopic dermatitis, give on empty stomach, expensive",
  },
  {
    brandName: "Atopica",
    commonDosing: "5mg/kg SID",
    controlledSubstance: false,
    form: "CAPSULE",
    genericName: "Cyclosporine",
    route: "ORAL",
    strength: "50mg",
    warnings: "For atopic dermatitis, give on empty stomach, expensive",
  },
];
