name: 'Setup VetMed Tracker Environment'
description: 'Sets up Node.js, pnpm, dependencies, and optionally mock database'
inputs:
  setup-db:
    description: 'Setup mock database environment variables'
    required: false
    default: 'false'
  node-version:
    description: 'The version of node to install (supports same inputs as actions/setup-node)'
    required: false
    default: '24'
outputs:
  database-url:
    description: 'Mock database URL'
    value: ${{ steps.setup-mock.outputs['database-url'] }}
  database-url-unpooled:
    description: 'Mock database URL without pooling'
    value: ${{ steps.setup-mock.outputs['database-url-unpooled'] }}
  nextauth-url:
    description: 'NextAuth URL for testing'
    value: ${{ steps.setup-mock.outputs['nextauth-url'] }}
  nextauth-secret:
    description: 'NextAuth secret for testing'
    value: ${{ steps.setup-mock.outputs['nextauth-secret'] }}

runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm install

    - name: Setup mock environment
      id: setup-mock
      shell: bash
      run: |
        # Set outputs for mock environment variables
        if [[ "${{ inputs.setup-db }}" == "true" ]]; then
          # noqa: CKV_SECRET_4 – mock credentials only
          echo "database-url=postgresql://mock:mock@localhost:5432/vetmed" >> $GITHUB_OUTPUT
          # noqa: CKV_SECRET_4 – mock credentials only
          echo "database-url-unpooled=postgresql://mock:mock@localhost:5432/vetmed?pool=false" >> $GITHUB_OUTPUT
          echo "nextauth-url=http://localhost:3000" >> $GITHUB_OUTPUT
          echo "nextauth-secret=mock-secret-for-testing" >> $GITHUB_OUTPUT
        else
          # Set empty outputs when not setting up mock DB
          echo "database-url=" >> $GITHUB_OUTPUT
          echo "database-url-unpooled=" >> $GITHUB_OUTPUT
          echo "nextauth-url=" >> $GITHUB_OUTPUT
          echo "nextauth-secret=" >> $GITHUB_OUTPUT
        fi
