import type { NewMedicationCatalog } from "../schema";

export const commonVeterinaryMedications: Omit<
	NewMedicationCatalog,
	"id" | "createdAt" | "updatedAt"
>[] = [
	// Antibiotics
	{
		genericName: "Amoxicillin",
		brandName: "Amoxi-Tabs",
		strength: "50mg",
		route: "ORAL",
		form: "TABLET",
		controlledSubstance: false,
		commonDosing: "10-20mg/kg BID",
		warnings: "Complete full course even if symptoms improve",
	},
	{
		genericName: "Amoxicillin",
		brandName: "Amoxi-Tabs",
		strength: "100mg",
		route: "ORAL",
		form: "TABLET",
		controlledSubstance: false,
		commonDosing: "10-20mg/kg BID",
		warnings: "Complete full course even if symptoms improve",
	},
	{
		genericName: "Amoxicillin",
		brandName: "Amoxi-Tabs",
		strength: "200mg",
		route: "ORAL",
		form: "TABLET",
		controlledSubstance: false,
		commonDosing: "10-20mg/kg BID",
		warnings: "Complete full course even if symptoms improve",
	},
	{
		genericName: "Cephalexin",
		brandName: "Rilexine",
		strength: "75mg",
		route: "ORAL",
		form: "TABLET",
		controlledSubstance: false,
		commonDosing: "15-25mg/kg BID",
		warnings: "Give with food to reduce stomach upset",
	},
	{
		genericName: "Cephalexin",
		brandName: "Rilexine",
		strength: "300mg",
		route: "ORAL",
		form: "TABLET",
		controlledSubstance: false,
		commonDosing: "15-25mg/kg BID",
		warnings: "Give with food to reduce stomach upset",
	},
	{
		genericName: "Enrofloxacin",
		brandName: "Baytril",
		strength: "22.7mg",
		route: "ORAL",
		form: "TABLET",
		controlledSubstance: false,
		commonDosing: "5mg/kg SID",
		warnings: "Avoid dairy products, monitor for joint issues in young animals",
	},
	{
		genericName: "Enrofloxacin",
		brandName: "Baytril",
		strength: "68mg",
		route: "ORAL",
		form: "TABLET",
		controlledSubstance: false,
		commonDosing: "5mg/kg SID",
		warnings: "Avoid dairy products, monitor for joint issues in young animals",
	},
	{
		genericName: "Clindamycin",
		brandName: "Antirobe",
		strength: "25mg",
		route: "ORAL",
		form: "CAPSULE",
		controlledSubstance: false,
		commonDosing: "5-10mg/kg BID",
		warnings: "Give with food, watch for diarrhea",
	},
	{
		genericName: "Clindamycin",
		brandName: "Antirobe",
		strength: "75mg",
		route: "ORAL",
		form: "CAPSULE",
		controlledSubstance: false,
		commonDosing: "5-10mg/kg BID",
		warnings: "Give with food, watch for diarrhea",
	},
	{
		genericName: "Metronidazole",
		brandName: "Flagyl",
		strength: "250mg",
		route: "ORAL",
		form: "TABLET",
		controlledSubstance: false,
		commonDosing: "7.5mg/kg BID",
		warnings: "Neurological side effects possible at high doses",
	},

	// Diabetes & Endocrine
	{
		genericName: "Insulin glargine",
		brandName: "Lantus",
		strength: "100 units/mL",
		route: "SC",
		form: "INJECTION",
		controlledSubstance: false,
		commonDosing: "Cats: 0.25-0.5 U/kg SC BID. Dogs: 0.25-0.5 U/kg SC BID",
		warnings: "Refrigerate. Monitor blood glucose. Never shake vial.",
	},
	{
		genericName: "Insulin NPH",
		brandName: "Humulin N",
		strength: "100 units/mL",
		route: "SC",
		form: "INJECTION",
		controlledSubstance: false,
		commonDosing: "Dogs: 0.5 U/kg SC BID. Cats: 1-3 U per cat BID",
		warnings: "Refrigerate. Roll gently to mix. Monitor blood glucose.",
	},
	{
		genericName: "Insulin detemir",
		brandName: "Levemir",
		strength: "100 units/mL",
		route: "SC",
		form: "INJECTION",
		controlledSubstance: false,
		commonDosing: "Cats: 0.5-1 U/kg SC BID",
		warnings: "Refrigerate. Do not mix with other insulins.",
	},
	{
		genericName: "Insulin glargine",
		brandName: "Lantus SoloStar",
		strength: "40 units",
		route: "SC",
		form: "INJECTION",
		controlledSubstance: false,
		commonDosing: "Cats: 0.25-0.5 U/kg SC BID",
		warnings:
			"Pre-filled pen. Refrigerate. Do not shake. Prime before first use.",
	},

	// Pain Management & NSAIDs
	{
		genericName: "Carprofen",
		brandName: "Rimadyl",
		strength: "25mg",
		route: "ORAL",
		form: "TABLET",
		controlledSubstance: false,
		commonDosing: "2mg/kg BID or 4mg/kg SID",
		warnings: "Monitor liver and kidney function, give with food",
	},
	{
		genericName: "Carprofen",
		brandName: "Rimadyl",
		strength: "75mg",
		route: "ORAL",
		form: "TABLET",
		controlledSubstance: false,
		commonDosing: "2mg/kg BID or 4mg/kg SID",
		warnings: "Monitor liver and kidney function, give with food",
	},
	{
		genericName: "Carprofen",
		brandName: "Rimadyl",
		strength: "100mg",
		route: "ORAL",
		form: "TABLET",
		controlledSubstance: false,
		commonDosing: "2mg/kg BID or 4mg/kg SID",
		warnings: "Monitor liver and kidney function, give with food",
	},
	{
		genericName: "Meloxicam",
		brandName: "Metacam",
		strength: "0.5mg/ml",
		route: "ORAL",
		form: "LIQUID",
		controlledSubstance: false,
		commonDosing: "0.1mg/kg SID",
		warnings: "Administer precise dose, monitor for GI upset",
	},
	{
		genericName: "Meloxicam",
		brandName: "Metacam",
		strength: "1.5mg/ml",
		route: "ORAL",
		form: "LIQUID",
		controlledSubstance: false,
		commonDosing: "0.1mg/kg SID",
		warnings: "Administer precise dose, monitor for GI upset",
	},
	{
		genericName: "Gabapentin",
		brandName: null,
		strength: "100mg",
		route: "ORAL",
		form: "CAPSULE",
		controlledSubstance: false,
		commonDosing: "5-10mg/kg BID-TID",
		warnings: "Start with low dose and titrate up, causes sedation initially",
	},
	{
		genericName: "Gabapentin",
		brandName: null,
		strength: "300mg",
		route: "ORAL",
		form: "CAPSULE",
		controlledSubstance: false,
		commonDosing: "5-10mg/kg BID-TID",
		warnings: "Start with low dose and titrate up, causes sedation initially",
	},
	{
		genericName: "Tramadol",
		brandName: null,
		strength: "50mg",
		route: "ORAL",
		form: "TABLET",
		controlledSubstance: true,
		commonDosing: "2-5mg/kg BID-TID",
		warnings: "Controlled substance, may cause sedation or excitement",
	},

	// Controlled Substances / Opioids
	{
		genericName: "Buprenorphine",
		brandName: "Buprenex",
		strength: "0.3mg/ml",
		route: "SC",
		form: "INJECTION",
		controlledSubstance: true,
		commonDosing: "0.01-0.03mg/kg q6-12h",
		warnings: "Controlled substance, respiratory depression possible",
	},
	{
		genericName: "Morphine",
		brandName: null,
		strength: "10mg/ml",
		route: "IM",
		form: "INJECTION",
		controlledSubstance: true,
		commonDosing: "0.1-1mg/kg q4-6h",
		warnings: "Controlled substance, monitor respiratory function",
	},

	// Sedatives/Anxiolytics
	{
		genericName: "Acepromazine",
		brandName: "PromAce",
		strength: "10mg",
		route: "ORAL",
		form: "TABLET",
		controlledSubstance: false,
		commonDosing: "0.25-1mg/kg PRN",
		warnings: "Do not use in seizure-prone animals, causes hypotension",
	},
	{
		genericName: "Acepromazine",
		brandName: "PromAce",
		strength: "10mg/ml",
		route: "IM",
		form: "INJECTION",
		controlledSubstance: false,
		commonDosing: "0.01-0.05mg/kg PRN",
		warnings: "Do not use in seizure-prone animals, causes hypotension",
	},
	{
		genericName: "Trazodone",
		brandName: null,
		strength: "50mg",
		route: "ORAL",
		form: "TABLET",
		controlledSubstance: false,
		commonDosing: "2-5mg/kg BID PRN",
		warnings: "May cause sedation, monitor for serotonin syndrome",
	},
	{
		genericName: "Alprazolam",
		brandName: "Xanax",
		strength: "0.25mg",
		route: "ORAL",
		form: "TABLET",
		controlledSubstance: true,
		commonDosing: "0.01-0.05mg/kg PRN",
		warnings: "Controlled substance, may cause paradoxical excitement",
	},

	// Cardiac Medications
	{
		genericName: "Enalapril",
		brandName: "Enacard",
		strength: "2.5mg",
		route: "ORAL",
		form: "TABLET",
		controlledSubstance: false,
		commonDosing: "0.25-0.5mg/kg BID",
		warnings: "Monitor kidney function and blood pressure",
	},
	{
		genericName: "Enalapril",
		brandName: "Enacard",
		strength: "5mg",
		route: "ORAL",
		form: "TABLET",
		controlledSubstance: false,
		commonDosing: "0.25-0.5mg/kg BID",
		warnings: "Monitor kidney function and blood pressure",
	},
	{
		genericName: "Furosemide",
		brandName: "Lasix",
		strength: "12.5mg",
		route: "ORAL",
		form: "TABLET",
		controlledSubstance: false,
		commonDosing: "1-2mg/kg BID-TID",
		warnings: "Monitor electrolytes and kidney function",
	},
	{
		genericName: "Furosemide",
		brandName: "Lasix",
		strength: "50mg",
		route: "ORAL",
		form: "TABLET",
		controlledSubstance: false,
		commonDosing: "1-2mg/kg BID-TID",
		warnings: "Monitor electrolytes and kidney function",
	},
	{
		genericName: "Pimobendan",
		brandName: "Vetmedin",
		strength: "1.25mg",
		route: "ORAL",
		form: "CAPSULE",
		controlledSubstance: false,
		commonDosing: "0.25mg/kg BID",
		warnings: "Give on empty stomach, monitor for arrhythmias",
	},
	{
		genericName: "Pimobendan",
		brandName: "Vetmedin",
		strength: "2.5mg",
		route: "ORAL",
		form: "CAPSULE",
		controlledSubstance: false,
		commonDosing: "0.25mg/kg BID",
		warnings: "Give on empty stomach, monitor for arrhythmias",
	},

	// Gastrointestinal
	{
		genericName: "Omeprazole",
		brandName: "Prilosec",
		strength: "20mg",
		route: "ORAL",
		form: "CAPSULE",
		controlledSubstance: false,
		commonDosing: "0.5-1mg/kg SID",
		warnings: "Give on empty stomach, long-term use may affect B12 absorption",
	},
	{
		genericName: "Famotidine",
		brandName: "Pepcid",
		strength: "10mg",
		route: "ORAL",
		form: "TABLET",
		controlledSubstance: false,
		commonDosing: "0.25-0.5mg/kg BID",
		warnings: "Safe for most animals, may interfere with some medications",
	},
	{
		genericName: "Maropitant",
		brandName: "Cerenia",
		strength: "16mg",
		route: "ORAL",
		form: "TABLET",
		controlledSubstance: false,
		commonDosing: "2mg/kg SID",
		warnings: "For prevention of motion sickness and vomiting",
	},
	{
		genericName: "Maropitant",
		brandName: "Cerenia",
		strength: "24mg",
		route: "ORAL",
		form: "TABLET",
		controlledSubstance: false,
		commonDosing: "2mg/kg SID",
		warnings: "For prevention of motion sickness and vomiting",
	},
	{
		genericName: "Sucralfate",
		brandName: "Carafate",
		strength: "1g",
		route: "ORAL",
		form: "TABLET",
		controlledSubstance: false,
		commonDosing: "0.5-1g TID",
		warnings: "Give on empty stomach, may bind other medications",
	},

	// Antihistamines/Allergy
	{
		genericName: "Diphenhydramine",
		brandName: "Benadryl",
		strength: "25mg",
		route: "ORAL",
		form: "TABLET",
		controlledSubstance: false,
		commonDosing: "1mg/kg BID-TID",
		warnings:
			"Causes drowsiness, avoid preparations with other active ingredients",
	},
	{
		genericName: "Loratadine",
		brandName: "Claritin",
		strength: "10mg",
		route: "ORAL",
		form: "TABLET",
		controlledSubstance: false,
		commonDosing: "0.25mg/kg SID",
		warnings: "Non-sedating antihistamine",
	},
	{
		genericName: "Cetirizine",
		brandName: "Zyrtec",
		strength: "10mg",
		route: "ORAL",
		form: "TABLET",
		controlledSubstance: false,
		commonDosing: "0.25-0.5mg/kg SID",
		warnings: "May cause mild sedation",
	},
	{
		genericName: "Hydroxyzine",
		brandName: "Atarax",
		strength: "10mg",
		route: "ORAL",
		form: "TABLET",
		controlledSubstance: false,
		commonDosing: "1-2mg/kg BID-TID",
		warnings: "Sedating antihistamine, useful for anxiety",
	},

	// Seizure Medications
	{
		genericName: "Phenobarbital",
		brandName: null,
		strength: "15mg",
		route: "ORAL",
		form: "TABLET",
		controlledSubstance: true,
		commonDosing: "1-3mg/kg BID",
		warnings: "Controlled substance, monitor liver function and drug levels",
	},
	{
		genericName: "Phenobarbital",
		brandName: null,
		strength: "30mg",
		route: "ORAL",
		form: "TABLET",
		controlledSubstance: true,
		commonDosing: "1-3mg/kg BID",
		warnings: "Controlled substance, monitor liver function and drug levels",
	},
	{
		genericName: "Potassium Bromide",
		brandName: "K-BroVet",
		strength: "250mg/ml",
		route: "ORAL",
		form: "LIQUID",
		controlledSubstance: false,
		commonDosing: "15-30mg/kg SID",
		warnings: "Give with food, long loading period required",
	},
	{
		genericName: "Levetiracetam",
		brandName: "Keppra",
		strength: "250mg",
		route: "ORAL",
		form: "TABLET",
		controlledSubstance: false,
		commonDosing: "10-20mg/kg TID",
		warnings: "Relatively safe, may cause sedation initially",
	},

	// Thyroid Medications
	{
		genericName: "Levothyroxine",
		brandName: "Soloxine",
		strength: "0.1mg",
		route: "ORAL",
		form: "TABLET",
		controlledSubstance: false,
		commonDosing: "10-20mcg/kg BID",
		warnings: "Give on empty stomach, monitor T4 levels",
	},
	{
		genericName: "Levothyroxine",
		brandName: "Soloxine",
		strength: "0.2mg",
		route: "ORAL",
		form: "TABLET",
		controlledSubstance: false,
		commonDosing: "10-20mcg/kg BID",
		warnings: "Give on empty stomach, monitor T4 levels",
	},
	{
		genericName: "Levothyroxine",
		brandName: "Soloxine",
		strength: "0.5mg",
		route: "ORAL",
		form: "TABLET",
		controlledSubstance: false,
		commonDosing: "10-20mcg/kg BID",
		warnings: "Give on empty stomach, monitor T4 levels",
	},
	{
		genericName: "Methimazole",
		brandName: "Tapazole",
		strength: "2.5mg",
		route: "ORAL",
		form: "TABLET",
		controlledSubstance: false,
		commonDosing: "2.5-5mg BID",
		warnings: "Monitor CBC and liver function, for hyperthyroidism",
	},

	// Topical/Ophthalmic/Otic
	{
		genericName: "Gentamicin/Betamethasone",
		brandName: "Gentocin Otic",
		strength: "3mg/ml + 1mg/ml",
		route: "OTIC",
		form: "DROPS",
		controlledSubstance: false,
		commonDosing: "2-4 drops BID",
		warnings: "For ear infections, do not use if eardrum is ruptured",
	},
	{
		genericName: "Tobramycin/Dexamethasone",
		brandName: "Tobradex",
		strength: "3mg/ml + 1mg/ml",
		route: "OPHTHALMIC",
		form: "DROPS",
		controlledSubstance: false,
		commonDosing: "1-2 drops TID-QID",
		warnings: "For eye infections, avoid with viral conditions",
	},
	{
		genericName: "Artificial Tears",
		brandName: "OptixCare",
		strength: null,
		route: "OPHTHALMIC",
		form: "DROPS",
		controlledSubstance: false,
		commonDosing: "1-2 drops PRN",
		warnings: "Safe for frequent use",
	},
	{
		genericName: "Mupirocin",
		brandName: "Muricin",
		strength: "2%",
		route: "TOPICAL",
		form: "OINTMENT",
		controlledSubstance: false,
		commonDosing: "Apply TID",
		warnings: "For skin infections, avoid contact with eyes",
	},
	{
		genericName: "Silver Sulfadiazine",
		brandName: "Silvadene",
		strength: "1%",
		route: "TOPICAL",
		form: "CREAM",
		controlledSubstance: false,
		commonDosing: "Apply BID",
		warnings: "For burn treatment, may cause temporary skin discoloration",
	},

	// Supplements/Vitamins
	{
		genericName: "Omega-3 Fatty Acids",
		brandName: "Welactin",
		strength: "1000mg",
		route: "ORAL",
		form: "CAPSULE",
		controlledSubstance: false,
		commonDosing: "1 capsule per 30lbs daily",
		warnings: "Support for skin, coat, and joint health",
	},
	{
		genericName: "Glucosamine/Chondroitin",
		brandName: "Cosequin",
		strength: "500mg/400mg",
		route: "ORAL",
		form: "TABLET",
		controlledSubstance: false,
		commonDosing: "1 tablet per 25lbs daily",
		warnings: "Joint support supplement, may take 4-6 weeks to see effects",
	},
	{
		genericName: "Probiotics",
		brandName: "FortiFlora",
		strength: "1g",
		route: "ORAL",
		form: "POWDER",
		controlledSubstance: false,
		commonDosing: "1 packet daily",
		warnings: "Digestive support, store in cool dry place",
	},

	// Parasiticides
	{
		genericName: "Ivermectin",
		brandName: "Heartgard",
		strength: "68mcg",
		route: "ORAL",
		form: "TABLET",
		controlledSubstance: false,
		commonDosing: "6mcg/kg monthly",
		warnings: "Contraindicated in MDR1 mutation breeds, heartworm prevention",
	},
	{
		genericName: "Fipronil",
		brandName: "Frontline",
		strength: "9.8%",
		route: "TOPICAL",
		form: "SPRAY",
		controlledSubstance: false,
		commonDosing: "Apply monthly",
		warnings: "Flea and tick prevention, avoid contact with treated areas",
	},
	{
		genericName: "Imidacloprid/Moxidectin",
		brandName: "Advantage Multi",
		strength: "10%/2.5%",
		route: "TOPICAL",
		form: "DROPS",
		controlledSubstance: false,
		commonDosing: "Apply monthly",
		warnings: "Broad spectrum parasite prevention",
	},
	{
		genericName: "Pyrantel Pamoate",
		brandName: "Nemex",
		strength: "50mg/ml",
		route: "ORAL",
		form: "LIQUID",
		controlledSubstance: false,
		commonDosing: "5mg/kg, repeat in 2 weeks",
		warnings: "Deworming medication, safe for puppies and kittens",
	},

	// Emergency/Injectable
	{
		genericName: "Epinephrine",
		brandName: "EpiPen",
		strength: "1mg/ml",
		route: "IM",
		form: "INJECTION",
		controlledSubstance: false,
		commonDosing: "0.01mg/kg IM",
		warnings: "Emergency use only for anaphylaxis",
	},
	{
		genericName: "Dexamethasone",
		brandName: "Azium",
		strength: "2mg/ml",
		route: "IV",
		form: "INJECTION",
		controlledSubstance: false,
		commonDosing: "0.1-2mg/kg",
		warnings: "Potent anti-inflammatory, multiple drug interactions",
	},
	{
		genericName: "Atropine",
		brandName: null,
		strength: "0.5mg/ml",
		route: "IM",
		form: "INJECTION",
		controlledSubstance: false,
		commonDosing: "0.02-0.04mg/kg",
		warnings: "For organophosphate poisoning and bradycardia",
	},

	// Additional Common Medications
	{
		genericName: "Prednisone",
		brandName: null,
		strength: "5mg",
		route: "ORAL",
		form: "TABLET",
		controlledSubstance: false,
		commonDosing: "0.5-2mg/kg SID-BID",
		warnings:
			"Taper dose gradually, monitor for side effects with long-term use",
	},
	{
		genericName: "Prednisone",
		brandName: null,
		strength: "10mg",
		route: "ORAL",
		form: "TABLET",
		controlledSubstance: false,
		commonDosing: "0.5-2mg/kg SID-BID",
		warnings:
			"Taper dose gradually, monitor for side effects with long-term use",
	},
	{
		genericName: "Prednisolone",
		brandName: null,
		strength: "5mg",
		route: "ORAL",
		form: "TABLET",
		controlledSubstance: false,
		commonDosing: "0.5-2mg/kg SID-BID",
		warnings: "Preferred over prednisone in cats, taper dose gradually",
	},
	{
		genericName: "Cyclosporine",
		brandName: "Atopica",
		strength: "25mg",
		route: "ORAL",
		form: "CAPSULE",
		controlledSubstance: false,
		commonDosing: "5mg/kg SID",
		warnings: "For atopic dermatitis, give on empty stomach, expensive",
	},
	{
		genericName: "Cyclosporine",
		brandName: "Atopica",
		strength: "50mg",
		route: "ORAL",
		form: "CAPSULE",
		controlledSubstance: false,
		commonDosing: "5mg/kg SID",
		warnings: "For atopic dermatitis, give on empty stomach, expensive",
	},
];
