name: Code Quality

on:
  push:
  pull_request:

jobs:
  biome_check:
    name: Biome Code Quality Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Run Biome CI Check
        run: biome ci . --reporter=github
