name: Code Quality

on:
  push:
  pull_request:

jobs:
  biome_check:
    name: Biome Code Quality Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Run Biome CI Check
        run: biome ci . --reporter=github

      # Add reviewdog for PR comments on pull requests
      - name: Run Biome with reviewdog
        if: github.event_name == 'pull_request'
        uses: mongolyy/reviewdog-action-biome@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
