name: Test

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: vetmed_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Setup test database
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/vetmed_test
          DATABASE_URL_POOLED: postgresql://postgres:postgres@localhost:5432/vetmed_test
          DATABASE_URL_UNPOOLED: postgresql://postgres:postgres@localhost:5432/vetmed_test
        run: |
          pnpm db:push

      - name: Run integration tests
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/vetmed_test
          DATABASE_URL_POOLED: postgresql://postgres:postgres@localhost:5432/vetmed_test
          DATABASE_URL_UNPOOLED: postgresql://postgres:postgres@localhost:5432/vetmed_test
          TEST_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/vetmed_test
          AUTH_SECRET: test-secret-key-for-testing
          AUTH_REDIRECT_PROXY_URL: http://localhost:3000/api/auth
          OPENAUTH_CLIENT_ID: test-client-id
          OPENAUTH_CLIENT_SECRET: test-client-secret
          OPENAUTH_ISSUER: https://auth.example.com
        run: pnpm test:integration

      - name: Install Playwright browsers
        run: pnpm playwright install --with-deps

      - name: Run E2E tests
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/vetmed_test
          DATABASE_URL_POOLED: postgresql://postgres:postgres@localhost:5432/vetmed_test
          DATABASE_URL_UNPOOLED: postgresql://postgres:postgres@localhost:5432/vetmed_test
          AUTH_SECRET: test-secret-key-for-testing
          AUTH_REDIRECT_PROXY_URL: http://localhost:3000/api/auth
          OPENAUTH_CLIENT_ID: test-client-id
          OPENAUTH_CLIENT_SECRET: test-client-secret
          OPENAUTH_ISSUER: https://auth.example.com
        run: pnpm test:e2e

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
